# Generated by Django 5.1.3 on 2024-12-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_districtlog_structure_count_and_more'),
        ('task_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='landmarks',
        ),
        migrations.CreateModel(
            name='TaskLandmarkComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_task_completions', to='structure.landmark')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_landmark_completions', to='task_flow.taskassign')),
            ],
            options={
                'db_table': 'tbl_task_landmark_complete',
                'unique_together': {('task', 'landmark')},
            },
        ),
    ]
