# Generated by Django 5.1.3 on 2024-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_districtlog_structure_count_and_more'),
        ('task_flow', '0002_assosiateduserslandmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='landmark',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='landmarks',
            field=models.ManyToManyField(related_name='task_assignments', to='structure.landmark'),
        ),
    ]
