# Generated by Django 5.1.3 on 2024-12-13 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_flow', '0003_remove_taskassign_landmark_taskassign_landmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('re_allocate_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_allocated_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_allocations', to='task_flow.taskassign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_allocations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_task_re_allocation',
            },
        ),
    ]
