# Generated by Django 5.1.3 on 2024-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_districtlog_structure_count_and_more'),
        ('task_flow', '0003_tasklandmarkcomplete_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklandmarkcomplete',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasklandmarkcomplete',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='landmarks',
            field=models.ManyToManyField(related_name='task_assignments', to='structure.landmark'),
        ),
    ]
