# Generated by Django 5.1.3 on 2024-12-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_flow', '0007_alter_taskmedia_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assosiateduserslandmark',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='assosiateduserslandmark',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tasklandmarkcomplete',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tasklandmarkcomplete',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='taskmedia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='taskmedia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='taskmedia',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
    ]
