# Generated by Django 5.1.3 on 2024-12-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_flow', '0008_assosiateduserslandmark_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
    ]
