# Generated by Django 5.1.3 on 2024-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_flow', '0009_alter_taskassign_latitude_alter_taskassign_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
    ]
