# Generated by Django 5.1.3 on 2024-12-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('task_flow', '0012_alter_tasklandmarkcomplete_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='task_flow.taskassign'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='scheduled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='django_celery_beat.crontabschedule'),
        ),
    ]
