# Generated by Django 5.1.3 on 2024-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_blood_group_remove_user_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
