# Generated by Django 5.1.3 on 2025-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_code',
        ),
    ]
