# Generated by Django 5.1.3 on 2025-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
