# Generated by Django 5.1.3 on 2025-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_group_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
