# Generated by Django 5.1.3 on 2025-02-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_bill_image_product_other_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerequest',
            name='approval',
        ),
        migrations.AddField(
            model_name='storerequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_emp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_product', to='store.product'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='status',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=0, max_length=50),
        ),
    ]
