# Generated by Django 5.1.3 on 2025-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storerequest_approval_storerequest_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='storerequest',
            name='items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
