# Generated by Django 5.1.3 on 2025-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_storerequest_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerequest',
            name='conversation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
