# Generated by Django 5.1.3 on 2025-02-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_storerequest_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerequest',
            name='conversation',
        ),
    ]
