# Generated by Django 5.1.3 on 2025-02-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_storerequest_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerequest',
            name='items',
        ),
    ]
