# Generated by Django 5.1.3 on 2025-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_storerequest_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='conversation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
