# Generated by Django 5.1.3 on 2025-02-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storerequest_conversation_storerequest_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='subject',
            field=models.CharField(blank=True, null=True),
        ),
    ]
