# Generated by Django 5.1.3 on 2025-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storerequest_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storerequest',
            options={'permissions': [('can_view_request', 'Can view store request'), ('can_approve_request', 'Can approve store request'), ('can_delete_request', 'Can delete store request')]},
        ),
    ]
