# Generated by Django 5.1.3 on 2025-02-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_storerequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storerequest',
            options={},
        ),
    ]
