# Generated by Django 5.1.3 on 2025-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_storerequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AlterField(
            model_name='storepurchase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
