# Generated by Django 5.1.3 on 2024-11-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_district',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_equipment',
            },
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_junction',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_zone',
            },
        ),
        migrations.CreateModel(
            name='DistrictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.district')),
            ],
            options={
                'db_table': 'tbl_log_district',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.equipment')),
            ],
            options={
                'db_table': 'tbl_log_equipment',
            },
        ),
        migrations.CreateModel(
            name='JunctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.junction')),
            ],
            options={
                'db_table': 'tbl_log_junction',
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='structure.district')),
            ],
            options={
                'db_table': 'tbl_landmark',
            },
        ),
        migrations.AddField(
            model_name='junction',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctions', to='structure.landmark'),
        ),
        migrations.CreateModel(
            name='LandmarkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.landmark')),
            ],
            options={
                'db_table': 'tbl_log_landmark',
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='structure.junction')),
            ],
            options={
                'db_table': 'tbl_pole',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='structure.pole'),
        ),
        migrations.CreateModel(
            name='PoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.pole')),
            ],
            options={
                'db_table': 'tbl_log_pole',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='structure.zone'),
        ),
        migrations.CreateModel(
            name='ZoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField()),
                ('current_values', models.JSONField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structure.zone')),
            ],
            options={
                'db_table': 'tbl_log_zone',
            },
        ),
    ]
